### ISSUE TITLE
AZERTY keyboards

### ISSUE THREAD

**Issue by bastienlaunay** [zachlatta/sshtron#10]
Doesn't works with AZERTY keyboards

**Comment by stek29** [comment]
use WASD :)

**Comment by stek29** [comment]
WASD or HJKL (vim) are supported 
What keys you want to use?

**Comment by bastienlaunay** [comment]
On an AZERTY keyboard, it's [QZSD](https://en.wikipedia.org/wiki/AZERTY)

**Comment by stek29** [comment]
I've created a pull request, waiting for @zachlatta now

**Comment by zachlatta** [comment]
Merged :ok_hand:

On Thu, Mar 10, 2016 at 8:16 AM, Soltan Tekeev <notifications@github.com>
wrote:

> I've created a pull request, waiting for @zachlatta
> <https://github.com/zachlatta> now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/10#issuecomment-194930798>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by bastienlaunay** [comment]
PERFECT ! Thanks 🍻
