### ISSUE TITLE
Need to change base image for RPI

### ISSUE THREAD

**Issue by FHowington** [zachlatta/sshtron#26]
apicht/rpi-golang:latest cannot be used for the RPI base image because it is a pre-1.10 go version and therefore does not have math/bits extension. A base such as resin/raspberry-pi-golang:latest will work.

**Comment by zachlatta** [comment]
Great, thanks for catching this. Would you be willing to take point on fixing this?

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by alyyousuf7** [comment]
Why is there a need for maths/lib package?

Is there any breaking changes in any of the packages we’re using?
