### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by FoxxMD** [zachlatta/sshtron#3]
Hitting the server is just causing my terminal to hang. Seems to enter into an ssh session but then nothing after that.

Tried on

* OSX 10.10.5 with zsh
* Ubuntu 14.04 with bash

[Other people](https://www.reddit.com/r/programming/comments/49f674/ssh_sshtronzachlattacom/d0s02eh) seem to be having problems too.

**Comment by ayooby** [comment]
me too. i can make ssh to sever.

**Comment by zachlatta** [comment]
I'm sorry about that, something caused the server to lock up. Just restarted it and it's working now!
