### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by grach0v** [zachlatta/sshtron#35]
When I run 
`ssh sshtron.zachlatta.com`
I get an error 
`Unable to negotiate with 149.28.243.27 port 22: no matching host key type found. Their offer: ssh-rsa`
Can you please explain what is wrong?

**Comment by gabmert** [comment]
You need to allow the deprecated rsa cipher for this connection. You can do this once via `ssh -o 'HostKeyAlgorithms +ssh-rsa' sshtron.zachlatta.com` or you can add following lines to `/etc/ssh/ssh_config`:
```
Host sshtron.zachlatta.com
   HostKeyAlgorithms +ssh-rsa
```
(if you are on linux)

**Comment by grach0v** [comment]
Thank you!
That helped
