### ISSUE TITLE
Segfault on build

### ISSUE THREAD

**Issue by aaronjeline** [zachlatta/sshtron#4]
Get a segfault on get, doesn't seem to leave a log anywhere. 
Any ideas?
If you need anything more please let me know, sorry I can't give you more off the bat.

**Comment by zachlatta** [comment]
What version of Go are you using?

On Tue, Mar 8, 2016 at 2:09 PM, aaronjeline <notifications@github.com>
wrote:

> Get a segfault on build, doesn't seem to leave a log anywhere.
> Any ideas?
> If you need anything more please let me know, sorry I can't give you more
> off the bat.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/4>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by aaronjeline** [comment]
4.9.3 (ran go version)
Thanks for the quick response.

**Comment by zachlatta** [comment]
Hmm, I don't think Go has a 4.9.3. version? Perhaps 1.4?

I'm able to compile with "go version go1.6 linux/amd64".

On Tue, Mar 8, 2016 at 2:14 PM, aaronjeline <notifications@github.com>
wrote:

> 4.9.3 (ran go version)
> Thanks for the quick response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/4#issuecomment-193990787>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by aaronjeline** [comment]
Alright got it to work. The go version in the Ubuntu repo has issues it seems.
Thanks for helping me out, and this is super cool.

**Comment by zachlatta** [comment]
Happy to help! And have fun :-).

On Tue, Mar 8, 2016 at 2:29 PM, aaronjeline <notifications@github.com>
wrote:

> Alright got it to work. The go version in the Ubuntu repo has issues it
> seems.
> Thanks for helping me out, and this is super cool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/4#issuecomment-193998660>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
