### ISSUE TITLE
Flickering display

### ISSUE THREAD

**Issue by TheThirdOne** [zachlatta/sshtron#5]
There is something weird with my terminal, but this is unplayable for me as between every frame there is a completely empty screen. 

I am not sure how you are rendering a new screen, but it seems like you are clearing the screen and the redrawing. If that can be rendered to a buffer which would then be pushed or render directly without clearing, I think that would help some people.

**Comment by zachlatta** [comment]
You just made me realize why the flickering is happening. Change incoming.

On Tue, Mar 8, 2016 at 2:53 PM, Benjamin Landers <notifications@github.com>
wrote:

> There is something weird with my terminal, but this is unplayable for me
> as between every frame there is a completely empty screen.
>
> I am not sure how you are rendering a new screen, but it seems like you
> are clearing the screen and the redrawing. If that can be rendered to a
> buffer which would then be pushed or render directly without clearing, I
> think that would help some people.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/5>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by TheThirdOne** [comment]
It should be just as simple as removing `\033[2J` right?

**Comment by zachlatta** [comment]
Just pushed and deployed a potential fix. I'm now sending the escape codes
to clear the screen as part of the new screen that's also sent over the
network (in the same buffer).

On Tue, Mar 8, 2016 at 2:59 PM, Benjamin Landers <notifications@github.com>
wrote:

> It should be just as simple as removing \033[2J right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/5#issuecomment-194007446>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
