### ISSUE TITLE
EU server?

### ISSUE THREAD

**Issue by klausenbusk** [zachlatta/sshtron#7]
170 ms make it a bit hard to play..
A EU server  could be nice.

**Comment by stek29** [comment]
+1

**Comment by zachlatta** [comment]
Would anyone be interested in hosting one? I'd be happy to throw it up at `eu.sshtron.zachlatta.com`.

**Comment by klausenbusk** [comment]
> Would anyone be interested in hosting one? I'd be happy to throw it up at eu.sshtron.zachlatta.com.

I have plenty of credits on my DO account, send me a mail on <github-username>@hotmail.com , and I can spin one up for you.
Any specific distro you want?

**Comment by zachlatta** [comment]
Shot you an email!

On Wed, Mar 9, 2016 at 10:02 AM, Kristian Klausen <notifications@github.com>
wrote:

> Would anyone be interested in hosting one? I'd be happy to throw it up at
> eu.sshtron.zachlatta.com.
>
> I have plenty of credits on my DO account, send me a mail on @hotmail.com
> , and I can spin one up for you.
> Any specific distro you want?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/7#issuecomment-194426496>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by stek29** [comment]
@zachlatta sorry for off top, how to set ports?

**Comment by zachlatta** [comment]
SSH_PORT for the SSH server's port and PORT for the HTTP server's port.

On Wed, Mar 9, 2016 at 10:07 AM, Soltan Tekeev <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> sorry for off top, how to set
> ports?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/7#issuecomment-194428961>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by stek29** [comment]
Ok I made one on DO Frankfurt 1, ip is 46.101.171.10
@zachlatta Could give you ssh access if you email me public key

**Comment by zachlatta** [comment]
Emailed!

On Wed, Mar 9, 2016 at 10:19 AM, Soltan Tekeev <notifications@github.com>
wrote:

> Ok I made one on DO Frankfurt 1, ip is 46.101.171.10
> @zachlatta <https://github.com/zachlatta> Could give you ssh access if
> you email me public key
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/7#issuecomment-194434323>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by stek29** [comment]
@zachlatta sorry but I can't find it, could you send email to `solteke.st at gmail dot com`?

**Comment by zachlatta** [comment]
And it's online!

    $ ssh eu.sshtron.zachlatta.com

Quick note: the primary server has a lot more CPU than the EU one, so we may run into performance issues in the EU.

**Comment by klausenbusk** [comment]
> Quick note: the primary server has a lot more CPU than the EU one, so we may run into performance issues in the EU.

What is the droplet size for the primary?

**Comment by zachlatta** [comment]
@stek29, you need to set the environment variables `SSH_PORT` and `PORT`.

Here's an example of what the commands may look like to start the server on another port (they assume you're in SSHTron's directory):

```
$ ssh-keygen -t rsa -f id_rsa
$ go get && go build
$ SSH_PORT=22 PORT=80 ./sshtron
```

> What is the droplet size for the primary?

It's currently scaled up to the 48GB & 16 core CPU plan, which is totally overkill. I'll probably scale it down over the next few days, but I gotta use that DigitalOcean credit something :-P. Let's just leave the EU server for now and see if it runs into performance issues as more people get on it. It was just holding up fine with 5 people online.

**Comment by stek29** [comment]
@zachlatta i've done already
i keep default one because i start it as user, but add some iptables rules
