### ISSUE TITLE
Nice project!

### ISSUE THREAD

**Issue by jpillora** [zachlatta/sshtron#8]
I wrote pretty much the same project about a year ago - feel free to grab some ideas from it:

https://github.com/jpillora/ssh-tron

You might see some performance benefits from sending screen deltas to each player? This reduces updates from WxH bytes to 2-8 bytes per tick

**Comment by zachlatta** [comment]
Ahah, what?! This is ridiculous. Same name too.

Congrats on the awesome project – will check out how you do screen deltas
for inspiration :-).

On Wed, Mar 9, 2016 at 6:01 PM, Jaime Pillora <notifications@github.com>
wrote:

> I wrote pretty much the same project about a year ago - feel free to grab
> some ideas from it:
>
> https://github.com/jpillora/ssh-tron
>
> You might see some performance benefits from sending screen deltas to each
> player? This reduces updates from WxH bytes to 2-8 bytes per tick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/8>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by jpillora** [comment]
I know, very strange! I saw this project in trending and I was very confused for a sec lol

Also, another note, I'm using braille chars in an attempt to get more square pixels. Since a single terminal char is more rectangular, it means you move faster up/down than you do left/right which can be unintuitive. However, fixing this means you need to map the game board of NxM to a terminal of NxM/2 which adds a bit of complexity.

**Comment by stek29** [comment]
+1 for mapping game board to NxM/2

**Comment by zachlatta** [comment]
Game board is actually already kind of indirectly mapped to NxM/2, if you
check out https://github.com/zachlatta/sshtron/blob/master/game.go#L79.

In SSHTron there isn't actually a game board, just a world height/weight
and floating point player positions. During rendering it's projected onto a
"board" (https://github.com/zachlatta/sshtron/blob/master/game.go#L493).
The vertical/horizontal movement speeds can be adjusted to better
compensate for the lack of square terminal colors. I didn't spend much time
tuning this. If anyone wants to improve it and submit a pull request, I'd
happily merge!

On Thu, Mar 10, 2016 at 5:36 AM, Soltan Tekeev <notifications@github.com>
wrote:

> +1 for mapping game board to NxM/2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/issues/8#issuecomment-194840552>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by stek29** [comment]
Oh that's why sometimes you it could be crosses of different color tails

**Comment by jpillora** [comment]
> Game board is actually already kind of indirectly mapped to NxM/2 ... The vertical/horizontal movement speeds can be adjusted to better compensate for the lack of square terminal colors

Exactly, mapping the game to NxM/2 gives you a **square** grid when combined with the right UTF8 chars. Slowed vertical movement helps though you still have less space to move in https://github.com/zachlatta/sshtron/blob/master/game.go#L309-L310

> there isn't actually a game board

Sorry, I'm referring to what you've called `level` https://github.com/zachlatta/sshtron/blob/master/game.go#L442
